project:
  name: wirevault
  description: QR-secured document portal for electrical sites

services:
  - name: wirevault-app
    type: web
    source:
      type: dockerfile
      path: .
      dockerfile: Dockerfile
    env:
      - key: ADDR
        value: ":8080"
    ports:
      - internal: 8080
    volumes:
      - name: wirevault-data
        mountPath: /app/data
      - name: wirevault-media
        mountPath: /app/media
    healthcheck:
      path: /
      interval: 30s
      timeout: 5s
      retries: 3
volumes:
  - name: wirevault-data
  - name: wirevault-media
